#pragma once

#define IDI_APP_ICON                     101
#define IDI_FOLDER_ICON                  102
#define IDI_SETTING_ICON                 103
#define IDI_UP_ARROW_ICON                104
#define IDI_TIME_ICON                    105
#define IDI_DELETE_TRASH_ICON            106
#define IDI_BUILTIN_CONTROL_PANEL         201
#define IDI_BUILTIN_TASK_MANAGER          202
#define IDI_BUILTIN_FILE_EXPLORER         203
#define IDI_BUILTIN_DEVICE_MANAGER        204
#define IDI_BUILTIN_DISK_MANAGEMENT       205
#define IDI_BUILTIN_SERVICES              206
#define IDI_BUILTIN_EVENT_VIEWER          207
#define IDI_BUILTIN_RESOURCE_MONITOR      208
#define IDI_BUILTIN_SYSTEM_INFORMATION    209
#define IDI_BUILTIN_REGISTRY_EDITOR       210
#define IDI_BUILTIN_CALCULATOR            211
#define IDI_BUILTIN_NOTEPAD               212
#define IDI_BUILTIN_COMMAND_PROMPT        213
#define IDI_BUILTIN_POWERSHELL            214
#define IDI_BUILTIN_ON_SCREEN_KEYBOARD    215
#define IDI_BUILTIN_BAIDU                 216
#define IDI_BUILTIN_GOOGLE                217
#define IDI_BUILTIN_GITHUB                218
#define IDI_BUILTIN_BILIBILI              219
#define IDI_BUILTIN_TAOBAO                220
#define IDI_BUILTIN_PING                  221
#define IDI_BUILTIN_IP_CONFIG             222
#define IDI_BUILTIN_LOCK_SCREEN           223
#define IDI_BUILTIN_HIBERNATE             224
#define IDI_BUILTIN_EMPTY_RECYCLE_BIN     225
